#pragma once
#include "gsl\gsl_cblas.h"
#include "cpuLU.h"
#include "Cholesky.h"
#include "LU.h"
#include "QR.h"
#include <time.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <string.h>
#include <cuda_runtime.h>
#include <cublas_v2.h>
#include <iomanip>
#include <cusolverDn.h>
#include <chrono>
#include <string>
#include <windows.h>